#!/bin/sh
# postinst script for flatmark

set -e

INSTALL_DIR="/opt/flatmark/bin/flatmark"

# Create a symbolic link to /usr/local/bin
if [ -x "$INSTALL_DIR" ]; then
    ln -sf "$INSTALL_DIR" /usr/local/bin/flatmark
fi

exit 0
