package ba.sake.flatmark.ssr

import ba.sake.sharaf.undertow.UndertowSharafServer
import ba.sake.sharaf.SharafHandler
import ba.sake.sharaf.utils.NetworkUtils

class GraphvizRendererSuite extends munit.FunSuite {

  var server: UndertowSharafServer = null
  var webDriverHolder: WebDriverHolder = WebDriverHolder()
  val port = NetworkUtils.getFreePort()

  override def beforeAll(): Unit =
    server = UndertowSharafServer("localhost", port, routes)
    server.start()

  override def afterAll(): Unit =
    server.stop()
    webDriverHolder.quit()

  test("render graphviz graph to SVG") {
    val ssr = FlatmarkSsr(s"http://localhost:${port}", webDriverHolder)
    val res = ssr.renderGraphviz("""digraph G {Hello->World}""", "dot")
    assertEquals(
      res,
      """<!--?xml version="1.0" encoding="UTF-8" standalone="no"?-->

<!-- Generated by graphviz version 12.2.1 (0)
 -->
<!-- Title: G Pages: 1 -->
<svg width="79pt" height="116pt" viewBox="0.00 0.00 79.41 116.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 112)">
<title>G</title>
<polygon fill="white" stroke="none" points="-4,4 -4,-112 75.41,-112 75.41,4 -4,4"></polygon>
<!-- Hello -->
<g id="node1" class="node">
<title>Hello</title>
<ellipse fill="none" stroke="black" cx="35.71" cy="-90" rx="32.49" ry="18"></ellipse>
<text text-anchor="middle" x="35.71" y="-85.8" font-family="Times,serif" font-size="14.00">Hello</text>
</g>
<!-- World -->
<g id="node2" class="node">
<title>World</title>
<ellipse fill="none" stroke="black" cx="35.71" cy="-18" rx="35.71" ry="18"></ellipse>
<text text-anchor="middle" x="35.71" y="-13.8" font-family="Times,serif" font-size="14.00">World</text>
</g>
<!-- Hello&#45;&gt;World -->
<g id="edge1" class="edge">
<title>Hello-&gt;World</title>
<path fill="none" stroke="black" d="M35.71,-71.7C35.71,-64.41 35.71,-55.73 35.71,-47.54"></path>
<polygon fill="black" stroke="black" points="39.21,-47.62 35.71,-37.62 32.21,-47.62 39.21,-47.62"></polygon>
</g>
</g>
</svg>
"""
    )
  }
}
