
name: Flatmark Docs
timezone: Europe/Sarajevo
lang: en

categories:
  tutorials:
    label: Tutorials
  howtos:
    label: How-to guides
  reference:
    label: Reference
  explanation:
    label: Explanation
