
name: My Cool Site
description: My Cool Site Description
timezone: Europe/Sarajevo

base_url: https://example.com

highlight_code: true
highlight_math: true

categories:
  docs:
    label: Documentation
    description: The documentation section of the site
  blog:
    label: Blog
    description: The blog section of the site
