
name: CI

on:
  push:
    branches: main
  pull_request:
  workflow_call:  # allow this workflow to be called from other workflows

jobs:
  build-installer:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            mill-module: ubuntu
            installer-name: flatmark-1.0.deb
            artifact-name: flatmark-installer-deb-x64
          - os: macos-latest
            mill-module: macos
            installer-name: flatmark-1.0.dmg
            artifact-name: flatmark-installer-macos-arm64
          - os: windows-latest
            mill-module: windows
            installer-name: flatmark-1.0.msi
            artifact-name: flatmark-installer-windows-x64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 24
      - run: |
          ./mill -i cli.${{ matrix.mill-module }}.jpackageAppImage2
      - name: Archive ${{ matrix.artifact-name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: out/cli/windows/jpackageAppImage2.dest/image/${{ matrix.flatmark-1.0.dmg }}
          retention-days: 30

  build-assembly-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - run: |
          ./mill -i cli.jvm.assembly
          cp out/cli/jvm/assembly.dest/out.jar flatmark
          cp out/cli/jvm/assembly.dest/out.jar flatmark.bat
      - name: Archive executable-jar
        uses: actions/upload-artifact@v4
        with:
          name: flatmark-executable-jar
          path: flatmark
          retention-days: 30
      - name: Archive executable-windows-jar
        uses: actions/upload-artifact@v4
        with:
          name: flatmark-executable-windows-jar
          path: flatmark.bat
          retention-days: 30

  build-native-executable:
    if: false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            original-exe-name: native-executable
            exe-name: flatmark
            artifact-name: flatmark-ubuntu-x64
          - os: macos-latest
            original-exe-name: native-executable
            exe-name: flatmark
            artifact-name: flatmark-macos-arm64
          - os: windows-latest
            original-exe-name: native-executable.exe
            exe-name: flatmark.exe
            artifact-name: flatmark-windows-x64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
      - run: |
          ./mill -i cli.jvm.nativeImage2
          cp out/cli/jvm/nativeImage2.dest/${{ matrix.original-exe-name }} ${{ matrix.exe-name }}
      - name: Archive native-executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.exe-name }}
          retention-days: 30
