
name: CI

on:
  push:
    branches: main
  pull_request:
  workflow_call:  # allow this workflow to be called from other workflows

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - run: |
          ./mill -i cli.assembly
          cp cli/assembly.dest/out.jar flatmark
          cp cli/assembly.dest/out.jar flatmark.bat
      - name: Archive native-executable
        uses: actions/upload-artifact@v4
        with:
          name: flatmark-executable-jar
          path: flatmark
          retention-days: 30
      - name: Archive native-executable
        uses: actions/upload-artifact@v4
        with:
          name: flatmark-executable-windows-jar
          path: flatmark.bat
          retention-days: 30

  build-native-executable:
    if: false
    name: build-native-executable
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            original-exe-name: native-executable
            exe-name: flatmark
            artifact-name: flatmark-ubuntu-x64
          - os: macos-latest
            original-exe-name: native-executable
            exe-name: flatmark
            artifact-name: flatmark-macos-arm64
          - os: windows-latest
            original-exe-name: native-executable.exe
            exe-name: flatmark.exe
            artifact-name: flatmark-windows-x64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
      - run: |
          ./mill -i cli.nativeImage2
          cp out/cli/nativeImage2.dest/${{ matrix.original-exe-name }} ${{ matrix.exe-name }}
      - name: Archive native-executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.exe-name }}
          retention-days: 30




